#!/bin/bash
export DATABASE_URL='DATABASE_URL='mysql://bc01f9fbfb6655:cf7bfad9@us-cdbr-east-03.cleardb.com/heroku_b5c088e89813acc?reconnect=true'

/home/cesaraugusto/projetos/Django-Portal/bin/python /home/cesaraugusto/projetos/Django-Portal/django_portal/manage.py runserver
#/opt/projetos/Django-Site/bin/python /opt/projetos/Django-Site/django_portal/manage.py run_gunicorn

#http://www.aprendendodjango.com/

#Produção
#http://senko.net/en/django-nginx-gunicorn/
#http://davidpoblador.com/run-django-apps-using-gunicorn-and-nginx/
